services:
  postgres:
    restart: always
    image: postgres:latest
    environment:
     POSTGRES_USER: postgres
     POSTGRES_PASSWORD: postgres
     POSTGRES_DATABASE: postgres
    ports:
      - 5432:5432
    volumes:
      - ./data/table.sql:/docker-entrypoint-initdb.d/01_table.sql
      - ./data/data.sql:/docker-entrypoint-initdb.d/02_table.sql

  # cassandra:
  #   restart: always
  #   image: cassandra:latest
  #   environment:
  #     CASSANDRA_CLUSTER_NAME: chatapp
  #   ports:
  #     - 9042:9042
  #   volumes:
  #     - ./data/table.cql:/docker-entrypoint-initdb.d/chat.cql

  mongo:
    image: mongo
    restart: always
    container_name: mongo_container 
    ports:
      - 27018:27017
    volumes:
      - ./data/mongodb:/docker-entrypoint-initdb.d/mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Abcd1234

  mongo-express:
    image: mongo-express:latest
    restart: always
    container_name: mongo_express_container
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: Abcd1234
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: Abcd1234
      ME_CONFIG_MONGODB_URL: mongodb://root:Abcd1234@mongo:27017/